# Fly configuration file for deploying applications.
#
# For more information, visit
# https://fly.io/docs/reference/configuration.

app = "auralmatics"
primary_region = "lax"

[build]
dockerfile = "Dockerfile"

[http_service]
force_https = true
internal_port = 8501
