# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: build

# Makes workflow run on any push or pull request.
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean
      job:
        default: lint
        description: CI job to run
        options:
          - lint
          - test
        type: choice

env:
  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
  PIP_DISABLE_PIP_VERSION_CHECK: "true"
  PIP_ROOT_USER_ACTION: ignore
  PLAYWRIGHT_BROWSERS_PATH: "${{ github.workspace }}/.cache/ms-playwright"
  POETRY_CACHE_DIR: "${{ github.workspace }}/.cache/pypoetry"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  PYTHON_KEYRING_BACKEND: "keyring.backends.null.Keyring"

jobs:
  lint:
    if: >-
      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'lint' }}
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            .cache
            .venv
          key: >-
            python-3.11_${{ runner.os }}_poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Node interpreter
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Prettier formatter
        run: |
          node --version
          npm --version
          npm install --global prettier
      - name: Check configuration file formatting
        run: prettier --check .
      - name: Install Python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python packages
        run: |
          python --version
          python -m pip --version
          python -m pip install poetry
          poetry lock --check
          poetry install --verbose
      - name: Run linter checks
        run: |
          poetry run bandit -ilr src
          poetry run black --check .
          poetry run flake8 .
          poetry run mypy .
          poetry build
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3

  test:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'test' }}
    name: Run unit test suite for Node 20 and Python 3.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            .cache
            .venv
          key: >-
            python-3.11_${{ runner.os }}_poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python packages
        run: |
          python --version
          python -m pip --version
          python -m pip install poetry
          poetry lock --check
          poetry install --verbose
          poetry run playwright install --with-deps chromium
      - name: Run test suite
        run: poetry run pytest --cov
      - name: Upload Playwright screenshots and videos if tests fail
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-captures
          path: tests/results
          retention-days: 30
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
