# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: release

# Makes workflow run on Git tag.
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean
      job:
        default: container
        description: CI job to run
        options:
          - container
          - deploy
          - release
        type: choice

jobs:
  container:
    if: >-
      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'container'
      }}
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "."
          file: Dockerfile
          push: true
          tags: |
            docker.io/scruffaluff/auralmatics:${{ github.ref_name }}
            docker.io/scruffaluff/auralmatics:latest
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3

  deploy:
    if: >-
      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'deploy' }}
    name: Deploy application to FlyIO
    needs: container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install FlyCTL
        run: |
          fly_uri="$(curl -LSfs https://api.fly.io/app/flyctl_releases/Linux/x86_64/latest)"
          curl -LSfs --output /tmp/flyctl.tar.gz "${fly_uri}"
          tar xf /tmp/flyctl.tar.gz --directory=/tmp
          sudo install /tmp/flyctl /usr/local/bin/flyctl
      - name: Deploy application
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        run: flyctl deploy
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3

  release:
    if: >-
      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'release' }}
    name: Make GitHub release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: >-
            See the
            [changelog](https://github.com/scruffaluff/auralmatics/blob/${{
            github.ref_name }}/CHANGELOG.md) for more information.
          name: Auralmatics ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
