# Streamlit configuration file.
#
# For more information, visit
# https://docs.streamlit.io/library/advanced-features/configuration.

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[global]
disableWatchdogWarning = true

[runner]
magicEnabled = false

[server]
address = "0.0.0.0"
fileWatcherType = "watchdog"
headless = true
runOnSave = true

[theme]
base = "light"
backgroundColor = "#fefefe"
primaryColor = "#c084fc"
